#FROM mcr.microsoft.com/dotnet/sdk:8.0
#FROM golang:1.23
#FROM node:18-alpine
FROM eclipse-temurin:21.0.5_11-jdk@sha256:a20cfa6afdbf57ff2c4de77ae2d0e3725a6349f1936b5ad7c3d1b06f6d1b840a
#RUN apk add --no-cache python3 make g++
#FROM python:3.12

COPY . .

CMD ["/bin/sh"]