services:
  
  frontend:
    image: registry.gitlab.com/sandesh-lab/microservices-demo/deploy:frontend
    restart: unless-stopped
    depends_on:
      - productcatalogservice
      - currencyservice
      - cartservice
      - checkoutservice
    networks:
      - front-tier
    ports:
      - 8080:8080
    environment:
      #- BASE_URL=""
      #- ENABLE_TRACING="0"
      #- ENABLE_PROFILER="0"
      - LISTEN_ADDR="0.0.0.0"
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:80
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8082
      - CHECKOUT_SERVICE_ADDR=checkoutservice:80
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - AD_SERVICE_ADDR=adservice:9555
      #- SHOPPING_ASSISTANT_SERVICE_ADDR=

  adservice:
    image: registry.gitlab.com/sandesh-lab/microservices-demo/deploy:adservice
    restart: unless-stopped
    networks:
      - front-tier
    ports:
      - 9555:9555
    environment:
      - PORT=9555
      #- DISABLE_STATS=""
      #- DISABLE_TRACING=""
    
  #shoppingassistantservice:
  #  image: registry.gitlab.com/sandesh-lab/microservices-demo/deploy:shoppingassistantservice
  #  restart: unless-stopped
  #  networks:
  #    - front-tier
    

  recommendationservice:
    image: registry.gitlab.com/sandesh-lab/microservices-demo/deploy:recommendationservice
    restart: unless-stopped
    networks:
      - front-tier
    ports:
      - 8082:8082
    environment:
      #- GCP_PROJECT_ID=""
      #- DISABLE_PROFILER=""
      #- ENABLE_TRACING="1"
      #- COLLECTOR_SERVICE_ADDR=""
      - PORT=8082
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550

  checkoutservice:
    #build:
    #  context: ../src/checkoutservice/
    image: registry.gitlab.com/sandesh-lab/microservices-demo/deploy:checkoutservice
    restart: unless-stopped
    depends_on:
      - shippingservice
      - productcatalogservice
      - cartservice
      - emailservice
      - paymentservice
    networks:
      - front-tier
    ports:
      - 9229:80
    environment:
      SHIPPING_SERVICE_ADDR: shippingservice:50051
      PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
      CART_SERVICE_ADDR: cartservice:80
      CURRENCY_SERVICE_ADDR: currencyservice:7000
      EMAIL_SERVICE_ADDR: emailservice:8081
      PAYMENT_SERVICE_ADDR: paymentservice:7001
  
  paymentservice:
    image: registry.gitlab.com/sandesh-lab/microservices-demo/deploy:paymentservice
    restart: unless-stopped
    networks:
      - front-tier
    ports:
      - 7001:7001
    environment:
      - PORT=7001
      - DISABLE_PROFILER=true
      #- ENABLE_TRACING="0"

  emailservice:
    image: registry.gitlab.com/sandesh-lab/microservices-demo/deploy:emailservice
    restart: unless-stopped
    networks:
      - front-tier
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      #- GCP_PROJECT_ID=""
      #- DISABLE_PROFILER=""
      #- ENABLE_TRACING="0"

  currencyservice:
    image: registry.gitlab.com/sandesh-lab/microservices-demo/deploy:currencyservice
    restart: unless-stopped
    networks:
      - front-tier
    ports:
      - 7000:7000
    environment:
      - PORT=7000
      - DISABLE_PROFILER=true

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "secret"]
    ports:
      - 6379:6379
    networks:
      - front-tier

  cartservice:
    image: registry.gitlab.com/sandesh-lab/microservices-demo/deploy:cartservice
    restart: unless-stopped
    networks:
      - front-tier
    ports:
      - 9000:80
    environment:
      REDIS_ADDR: redis:6379,password=secret,defaultDatabase=1
      #SPANNER_PROJECT:
      #SPANNER_CONNECTION_STRING:
      #ALLOYDB_PRIMARY_IP:

  productcatalogservice:
    image: registry.gitlab.com/sandesh-lab/microservices-demo/deploy:productcatalogservice
    restart: unless-stopped
    networks:
      - front-tier
    ports:
      - 3550:3550
    environment:
      PORT: 3550
      #ENABLE_TRACING: 0
      #DISABLE_PROFILER: ""
      #EXTRA_LATENCY: ""
      #COLLECTOR_SERVICE_ADDR: 

  shippingservice:
    image: registry.gitlab.com/sandesh-lab/microservices-demo/deploy:shippingservice
    restart: unless-stopped
    networks:
      - front-tier
    ports:
      - 50051:50051
    environment:
      PORT: 50051
      #DISABLE_TRACING:
      #DISABLE_PROFILER:
      #DISABLE_STATS:

networks:
  front-tier: