FROM --platform=$BUILDPLATFORM eclipse-temurin:21.0.5_11-jre-alpine@sha256:4300bfe1e11f3dfc3e3512f39939f9093cf18d0e581d1ab1ccd0512f32fe33f0

WORKDIR /app

COPY --from=gitlab-artifact /build ./

EXPOSE 9555
ENTRYPOINT ["/app/build/install/hipstershop/bin/AdService"]